import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from '@playwright/test/reporter';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Markdownレポーター
 *
 * テスト結果をMarkdown形式で出力
 * GitHubのPRコメントやSlack通知に使用可能
 */

interface TestInfo {
  test: TestCase;
  result: TestResult;
}

class MarkdownReporter implements Reporter {
  private startTime: Date;
  private tests: TestInfo[] = [];
  private config!: FullConfig;

  constructor() {
    this.startTime = new Date();
  }

  onBegin(config: FullConfig, _suite: Suite) {
    this.config = config;
  }

  onTestEnd(test: TestCase, result: TestResult) {
    this.tests.push({ test, result });
  }

  onEnd(result: FullResult) {
    const endTime = new Date();
    const duration = endTime.getTime() - this.startTime.getTime();

    const passed = this.tests.filter((t) => t.result.status === 'passed').length;
    const failed = this.tests.filter(
      (t) => t.result.status === 'failed' || t.result.status === 'timedOut'
    ).length;
    const skipped = this.tests.filter((t) => t.result.status === 'skipped').length;

    // Markdown生成
    let md = this.generateMarkdown({
      duration,
      passed,
      failed,
      skipped,
      total: this.tests.length,
      status: result.status,
    });

    // ファイルに出力
    const outputDir = 'test-results';
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const outputPath = path.join(outputDir, 'test-report.md');
    fs.writeFileSync(outputPath, md);

    console.log(`📝 Markdownレポート: ${outputPath}`);
  }

  private generateMarkdown(stats: {
    duration: number;
    passed: number;
    failed: number;
    skipped: number;
    total: number;
    status: FullResult['status'];
  }): string {
    const statusEmoji = stats.status === 'passed' ? '✅' : '❌';
    const statusText = stats.status === 'passed' ? '成功' : '失敗';

    let md = `# ${statusEmoji} テストレポート\n\n`;
    md += `**実行日時**: ${this.startTime.toLocaleString('ja-JP')}\n\n`;

    // サマリーテーブル
    md += `## 📊 サマリー\n\n`;
    md += `| 項目 | 値 |\n`;
    md += `|------|----|\n`;
    md += `| ステータス | ${statusEmoji} ${statusText} |\n`;
    md += `| 実行時間 | ${(stats.duration / 1000).toFixed(2)}秒 |\n`;
    md += `| 総テスト数 | ${stats.total} |\n`;
    md += `| ✅ 成功 | ${stats.passed} |\n`;
    md += `| ❌ 失敗 | ${stats.failed} |\n`;
    md += `| ⏭️ スキップ | ${stats.skipped} |\n`;
    md += `| 成功率 | ${((stats.passed / stats.total) * 100).toFixed(1)}% |\n\n`;

    // プロジェクト別結果
    const byProject = this.groupByProject();
    if (Object.keys(byProject).length > 1) {
      md += `## 📁 プロジェクト別\n\n`;
      md += `| プロジェクト | 成功 | 失敗 | 合計 |\n`;
      md += `|------------|------|------|------|\n`;
      for (const [name, tests] of Object.entries(byProject)) {
        const p = tests.filter((t) => t.result.status === 'passed').length;
        const f = tests.filter(
          (t) => t.result.status === 'failed' || t.result.status === 'timedOut'
        ).length;
        const emoji = f > 0 ? '❌' : '✅';
        md += `| ${emoji} ${name} | ${p} | ${f} | ${tests.length} |\n`;
      }
      md += '\n';
    }

    // 失敗したテスト
    const failures = this.tests.filter(
      (t) => t.result.status === 'failed' || t.result.status === 'timedOut'
    );
    if (failures.length > 0) {
      md += `## ❌ 失敗したテスト\n\n`;
      for (const { test, result } of failures) {
        const projectName = test.parent.project()?.name || 'default';
        md += `### ${test.title}\n\n`;
        md += `- **プロジェクト**: ${projectName}\n`;
        md += `- **ファイル**: \`${path.basename(test.location.file)}:${test.location.line}\`\n`;
        md += `- **実行時間**: ${(result.duration / 1000).toFixed(2)}秒\n\n`;
        if (result.error) {
          md += `**エラー**:\n\`\`\`\n${result.error.message?.slice(0, 500) || 'Unknown error'}\n\`\`\`\n\n`;
        }
      }
    }

    // 遅いテスト
    const slowTests = this.tests
      .filter((t) => t.result.status === 'passed')
      .sort((a, b) => b.result.duration - a.result.duration)
      .slice(0, 5);

    if (slowTests.length > 0) {
      md += `## 🐢 遅いテスト (Top 5)\n\n`;
      md += `| テスト | 実行時間 |\n`;
      md += `|--------|----------|\n`;
      for (const { test, result } of slowTests) {
        md += `| ${test.title} | ${(result.duration / 1000).toFixed(2)}秒 |\n`;
      }
      md += '\n';
    }

    // フッター
    md += `---\n\n`;
    md += `*Generated by Playwright Custom Reporter*\n`;

    return md;
  }

  private groupByProject(): Record<string, TestInfo[]> {
    const result: Record<string, TestInfo[]> = {};
    for (const info of this.tests) {
      const name = info.test.parent.project()?.name || 'default';
      if (!result[name]) {
        result[name] = [];
      }
      result[name].push(info);
    }
    return result;
  }
}

export default MarkdownReporter;
